services:
  airflow:
    image: ikunalchhabra/airflow-datascience:latest
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./dags:/airflow/dags
      - ./notebooks:/airflow/notebooks
